In [78]:
import pandas as pd
import numpy as np

In [79]:
train = pd.read_csv('titanic_train.csv')
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [80]:
train.drop(columns=  [ 'PassengerId','Cabin' ,'Ticket' , 'Name' ], inplace = True)

In [81]:
train.sample(5)

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
308         0       2    male  30.0      1      0  24.0000        C
468         0       3    male   NaN      0      0   7.7250        Q
10          1       3  female   4.0      1      1  16.7000        S
877         0       3    male  19.0      0      0   7.8958        S
24          0       3  female   8.0      3      1  21.0750        S

In [82]:
train.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [83]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train , y_test = train_test_split(train.drop(columns= ['Survived']) , train['Survived'] ,test_size=0.2 , random_state=42 , stratify = train['Survived'])

In [84]:
from sklearn.impute import KNNImputer
ki = KNNImputer(n_neighbors=10)

In [85]:
x_train_trf = ki.fit_transform(x_train[x_train.select_dtypes(include='number').columns])
x_test_trf = ki.transform(x_test[x_train.select_dtypes(include='number').columns])

In [86]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

lr.fit(x_train_trf, y_train)

pred = lr.predict(x_test_trf)

In [87]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test , pred)

In [88]:
accuracy

0.6815642458100558